# Generated by Django 4.1.3 on 2022-11-28 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0001_initial'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyincome',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='WeeklySalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_week', models.DateField()),
                ('salary', models.IntegerField(default=0)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary', to='courier.courier')),
            ],
        ),
    ]
